query getAllTasks($userId: Float!) {
  task(userId: $userId) {
    id
    title
    status {
      id
      name
    }
    statusId
    date
    memo
  }
}

mutation createTask($input: createTaskInput!) {
  createTask(createTaskInput: $input) {
      title
      memo
      date
      status {
        id
        name
      }
      userId
  }
}

mutation updateTask($taskId: Float!, $input: createTaskInput!) {
  updateTask(taskId: $taskId, createTaskInput: $input) {
    id
  }
}

mutation deleteTask($taskId: Float!) {
  deleteTask(taskId: $taskId) {
    id
  }
}