query getAllTasks {
  task {
    id
    title
  }
}

mutation createTask($input: createTaskInput!) {
  createTask(createTaskInput: $input) {
      title
      memo
      date
      statusId
      userId
  }
}