query getAllTasks($userId: Float!) {
  task(userId: $userId) {
    id
    title
    status {
      id
      name
    }
    statusId
    date
    memo
  }
}

mutation createTask($input: createTaskInput!) {
  createTask(createTaskInput: $input) {
      title
      memo
      date
      status {
        id
        name
      }
      userId
  }
}