query getUser($email: String!) {
  user(email: $email) {
    id
    email
  }
} 

mutation createUser($input: createUserInput!) {
  createUser(createUserInput: $input) { 
    uuid
    name
    email
  }
} 